### ISSUE TITLE
Crash when pressing cast button on android

### ISSUE THREAD

**Issue by RahnRazamai** [flextv/react-native-google-cast#17]
Hi, I am using this version as i want to add custom receiver for my cast app.

done everything that you guys put in the readme. but when click on the cast button my app crashes. here is the log
07-18 18:03:36.152 23581-23581/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: my.com.tonton.mobile.alpha, PID: 23581
    java.lang.IllegalStateException: The activity must be a subclass of FragmentActivity
        at android.support.v7.app.MediaRouteButton.showDialog(MediaRouteButton.java:242)
        at android.support.v7.app.MediaRouteButton.performClick(MediaRouteButton.java:303)
        at android.view.View$PerformClick.run(View.java:22433)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6236)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
07-18 18:09:01.570 24809-24809/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: my.com.tonton.mobile.alpha, PID: 24809
    java.lang.IllegalStateException: The activity must be a subclass of FragmentActivity
        at android.support.v7.app.MediaRouteButton.showDialog(MediaRouteButton.java:242)
        at android.support.v7.app.MediaRouteButton.performClick(MediaRouteButton.java:303)
        at android.view.View$PerformClick.run(View.java:22433)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6236)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
got any idea why this happens?

**Comment by RahnRazamai** [comment]
Found the solution. lol. looks like we need to change mainactivity.java extends from ReactActivity to ReactFragmentActivity. that did it. Thanks for this awesome cast library guys!
